### model
model_name_or_path: ../../model.Qwen/Qwen3-0.6B
trust_remote_code: true

### method
stage: pt
do_train: true
finetuning_type: full

### dataset
dataset_dir: ./data
dataset: data1
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: output/full/pretrain
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-5    # ⬇️ 全参一般要比 LoRA 小
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
